#!/bin/bash

env >> /tmp/vars.auth
echo >> /tmp/vars.auth

QUERY="AUTH
ap_id=${NAS_IDENTIFIER//\"/}
user_id=${USER_NAME//\"/}
ud_mac=${CALLING_STATION_ID//\"/}
session=${ACCT_SESSION_ID//\"/}

"

nc -q 2 localhost 2337 <<< "$QUERY"
